// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ScanConfig {
    subnet: string;
    threadLimit: number;
    delayMs: number;
}

export type ScanStatus = "idle" | "running" | "paused" | "cancelled" | "completed";

export interface ScanProgress {
    total: number;
    completed: number;
    active: number;
    status: ScanStatus;
}

export interface ScanResult {
    ip: string;
    reachable: boolean;
    latencyMs: number;
    error?: string;
}

export interface ScanSnapshot {
    config: ScanConfig;
    progress: ScanProgress;
    results: ScanResult[];
    updated: string;
}

export interface ScanUpdate {
    result: ScanResult;
    progress: ScanProgress;
}

export function StartScan(arg1: ScanConfig): Promise<ScanSnapshot>;

export function PauseScan(): Promise<ScanProgress>;

export function ResumeScan(): Promise<ScanProgress>;

export function CancelScan(): Promise<ScanProgress>;

export function GetSnapshot(): Promise<ScanSnapshot>;

export function ExportResults(): Promise<string>;

export function ImportResults(arg1: string): Promise<ScanSnapshot>;
