// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scan} from '../models';

export function CancelScan():Promise<scan.Progress>;

export function ExportResults():Promise<string>;

export function GetSnapshot():Promise<scan.Snapshot>;

export function ImportResults(arg1:string):Promise<scan.Snapshot>;

export function PauseScan():Promise<scan.Progress>;

export function ResumeScan():Promise<scan.Progress>;

export function StartScan(arg1:scan.Config):Promise<scan.Snapshot>;
