// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function ExportResults() {
  return window['go']['main']['App']['ExportResults']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function ImportResults(arg1) {
  return window['go']['main']['App']['ImportResults'](arg1);
}

export function PauseScan() {
  return window['go']['main']['App']['PauseScan']();
}

export function ResumeScan() {
  return window['go']['main']['App']['ResumeScan']();
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}
